### ISSUE TITLE
Full stops, exclamation points and question marks (with no space afterward) issue.

### ISSUE THREAD

**Issue by SoulReaverFan** [zaggo/PleasantTranslate#2]
Hi again. Thank you for the great application.

I noticed an issue where if there are full stops, exclamation points or question marks in a sentence on a line that looks like this for example.

“See? This app is great. Fact.”

then the final translated srt will look like this with no space after full stops and question marks.

“Ser du?Denne app er fantastisk.Fakta”

Same thing will happen with exclamation points and maybe other symbols I haven’t noticed yet.

Thanks in advance for your help 😊

**Comment by zaggo** [comment]
Fixed in v1.1
